// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID string `json:"id" db:"id"`
	Text string `json:"text" db:"todo_text"`
	Done bool `json:"done" db:"done"`
	User *User `json:"user" db:"user_id"`
}
type User struct {
	ID string `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
}

type NewTodo struct {
	Text string `json:"text"`
	UserID string `json:"userId"`
}

// type NewTodo struct {
// 	Text   string `json:"text"`
// 	UserID string `json:"userId"`
// }

// type Todo struct {
// 	ID   string `json:"id"`
// 	Text string `json:"text"`
// 	Done bool   `json:"done"`
// 	User *User  `json:"user"`
// }

// type User struct {
// 	ID   string `json:"id"`
// 	Name string `json:"name"`
// }
